CREATE TABLE `copsoq_assessments` (
	`id` varchar(64) NOT NULL,
	`tenantId` varchar(64) NOT NULL,
	`sectorId` varchar(64),
	`title` varchar(255) NOT NULL,
	`description` text,
	`assessmentDate` timestamp NOT NULL,
	`status` enum('draft','in_progress','completed','reviewed') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `copsoq_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `copsoq_reports` (
	`id` varchar(64) NOT NULL,
	`assessmentId` varchar(64) NOT NULL,
	`tenantId` varchar(64) NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`totalRespondents` int,
	`responseRate` int,
	`averageDemandScore` int,
	`averageControlScore` int,
	`averageSupportScore` int,
	`averageLeadershipScore` int,
	`averageCommunityScore` int,
	`averageMeaningScore` int,
	`averageTrustScore` int,
	`averageJusticeScore` int,
	`averageInsecurityScore` int,
	`averageMentalHealthScore` int,
	`averageBurnoutScore` int,
	`averageViolenceScore` int,
	`lowRiskCount` int,
	`mediumRiskCount` int,
	`highRiskCount` int,
	`criticalRiskCount` int,
	`reportUrl` varchar(500),
	`generatedAt` timestamp,
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `copsoq_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `copsoq_responses` (
	`id` varchar(64) NOT NULL,
	`assessmentId` varchar(64) NOT NULL,
	`personId` varchar(64) NOT NULL,
	`tenantId` varchar(64) NOT NULL,
	`ageGroup` varchar(20),
	`hasDisability` boolean,
	`disabilityType` varchar(255),
	`gender` varchar(20),
	`maritalStatus` varchar(20),
	`childrenCount` varchar(20),
	`education` varchar(50),
	`yearsInCompany` varchar(20),
	`alcoholFrequency` varchar(20),
	`smokeFrequency` varchar(20),
	`recommendationScore` int,
	`responses` json,
	`demandScore` int,
	`controlScore` int,
	`supportScore` int,
	`leadershipScore` int,
	`communityScore` int,
	`meaningScore` int,
	`trustScore` int,
	`justiceScore` int,
	`insecurityScore` int,
	`mentalHealthScore` int,
	`burnoutScore` int,
	`violenceScore` int,
	`overallRiskLevel` enum('low','medium','high','critical'),
	`mentalHealthSupport` text,
	`workplaceImprovement` text,
	`isAnonymous` boolean DEFAULT false,
	`completedAt` timestamp,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `copsoq_responses_id` PRIMARY KEY(`id`)
);
